[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "4ff2d0239ee573688af35474c6e436b07e1de5c6"
os = "macos"

    [[proxTV.download]]
    sha256 = "a2f235bf42f4fc76949ba4bbfbabeda0da0e38da546ce31c2240f8e7f115f1c1"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.aarch64-apple-darwin.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "f224d79b4922d92e916c7a6c6947a76946fd600f"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "0087f25909a4f8cc18fd15fee44b5e915fe79124fec916cf75ee469c77e06df8"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.aarch64-linux-gnu.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "43a3fe56c0d6538b5b7a8a04a9d0b76e660b2aa0"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "ee90d3f76cd7653ff75623b486ceb3ca9e3e184b06c61c25e461f86056ca9c6e"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.aarch64-linux-musl.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e52ca0e97233ae25d56939b264ca0e8520cf4d4"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "fc64d65b1e2915cd02c0913bc0e8f56a19a357c2fa8cbcf47730aa0e488a97cd"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.armv6l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d27cf5526313075035937cf1372cd89a942e2019"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "85d2979dbae9ab564aae9844146b2ee321d166bf72dfe42763ee5d8d44c44e6b"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.armv6l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a967b9ae8b29f97a595c0b2e735015470f0028e"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "663e0cf8b2f6f3c52754f4ad685c1e5de8e16d65ffaabd5f6984759c0068e169"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.armv7l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67213d9e3df69e68da67b59caf28ed61d36c25e9"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "eec56523131d3f1083dc7231bbd56b72e19b4433c00f820d0d5f9a3eb96a1bd5"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.armv7l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "81927459d678bd8ead2d69b8fc28f433efd16195"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "49215cc471f63b5cd3b7f46522c4e1d4b34e9b9b8333ad0e63c5bf709d75c2a7"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.i686-linux-gnu.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "8da586e63cd564bfba312c6b37372e20142ef77d"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "0cc9914f0342e9b296cd4c145357308367341bd9244f98a0543be8978b0b9478"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.i686-linux-musl.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "be6bb430d12c3574666e0542c7b9dca227fe8ce6"
os = "windows"

    [[proxTV.download]]
    sha256 = "8067c49b35a48a9a83ecd2f1b1ca4cd986d5ddbb010cbf87971f3b1b66495d82"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.i686-w64-mingw32.tar.gz"
[[proxTV]]
arch = "powerpc64le"
git-tree-sha1 = "0bd3ee90d38b0f30d046385a173979c17979fd56"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "f48b883f47fb9e28124e0b1347c9ebf190715eca97ee09d47e4822567629d298"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.powerpc64le-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "e0d0887099286a9d8cdc2c20e431a3e82bbc435d"
os = "macos"

    [[proxTV.download]]
    sha256 = "93fbd0d7682fbe52be837eb41a6c75307c581c42e72338c9ab674ecd23edfe0c"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.x86_64-apple-darwin.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "6774d29d405a83a1c45fa497ccf10443f43869e1"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "170d1117bbf78b1872ab33b5dff1f362a8a4de63216218227ce5040d0c86182a"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.x86_64-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "a1ff09056c2cfbead56ebca66b485b3d2677a23e"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "68cffb46e94572fca9505bb0a39e250dc772f4615d05fb1e0bec6a8270ce8694"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.x86_64-linux-musl.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "3fd9c051b85ec44e51a33503cebbcb675785299c"
os = "freebsd"

    [[proxTV.download]]
    sha256 = "ad6cc0c5995ed64a0208128960779e02faa4e9995e72e9755968641e06efd32b"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.x86_64-unknown-freebsd.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "54eee5b483046cd464741dd8196efa25f81c4889"
os = "windows"

    [[proxTV.download]]
    sha256 = "1c9e508c104c0a6dc7847a9a329ac165e42e1a061323cfdb8c15757c578d967c"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.1+0/proxTV.v3.3.1.x86_64-w64-mingw32.tar.gz"
