[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "01119c8ac1b5d109be786ab430bf93c81f25a569"
os = "macos"

    [[proxTV.download]]
    sha256 = "6aaf7b1079f5ba0e9aaea4cb25e6a68cdd31c5d79b5ff9c4da1bcf5a8ff374f6"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.aarch64-apple-darwin.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "d605f6ca7b648f28902f0ff01f0a0f137072165b"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "96b6edffb4b839580d371fde6a50c4eaa960e6188fa54abfb2d4c4e46d76d6f3"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.aarch64-linux-gnu.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "239043339cb0ebf1084b14186a8176ce4d6dd2df"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "5f7a6a05ceff1afb7e7c232570b46ba7f743973cb089782026030e0f17656f60"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.aarch64-linux-musl.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7930d418a2fd6b9845fe1a3038d8c3720962cac7"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "5f20d5a4b5630682e991962282072bea8459d4194236cd473fa170acb4c0e672"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.armv6l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a1dbab705d3d250c07fd15f62a5a1b6b8ede6a64"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "5776d06d9c303bd1d1d2a26863d2bc5091d395feb1d23fd9f66787f47849d599"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.armv6l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01ab4d2c7f3c18e73b7ccced47a631b8ca12f137"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "4a43f157217f9e410be689a094bf769a1d4d418fa6177798d9c5bd3101caf9fd"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.armv7l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "16e6624b9b85111774fa80c14fed82728d6aa315"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "a894b7d9ed7f9938c5a6cfeb64dc59afbe86bb6963c2c5636d409f6b55a36806"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.armv7l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "fb982b4789e5cf275d3ae03d36091802ae57e9eb"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "505e230a61bd6a70a9b577ad00a7e76506b3b5657a7b37d93a3a88e6f97a7bd2"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.i686-linux-gnu.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "d866902a18c219ed1a370e96e263a10226860f5a"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "6fa93d2087f36c8fd355809713905ab6ba1a6a2c2081c659bea50e48af78ca16"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.i686-linux-musl.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "6d3fc65b326720fb67ae6eaa05635ed7a0b1f1cc"
os = "windows"

    [[proxTV.download]]
    sha256 = "f0a44f81e4a02c58c1f697d546e03584cf67b9dc8f6756324c9c4f2980c60b9d"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.i686-w64-mingw32.tar.gz"
[[proxTV]]
arch = "powerpc64le"
git-tree-sha1 = "3bd4973fbab9ad5c781f58beef16d18e796e7ffc"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "47f7d935980e93b39c0f2ef0dc0f1d6ba40a316df7f7a21d43cc49d19b4d57e0"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.powerpc64le-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "cc663a559076198e41d5dae254249f1d54068bf2"
os = "macos"

    [[proxTV.download]]
    sha256 = "2a5ef12eceecd112e7186051b4186b89b7bafd6b8ffd53add31d72816023d1aa"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.x86_64-apple-darwin.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "4378d837d77bd6e04e865f8f5621744bca06c440"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "afd2c8a014342ab693d749e01c2fbf7c01a94834b6698a5b3c3a21e6a70cebd7"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.x86_64-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "140596e9854b3667622af782d839287c950d0da5"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "1dba2833b1f607d23933f5c9455d7c6432f16c027b0507deb46cb8cf99a8919f"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.x86_64-linux-musl.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "67e123d30abdbe9f27586226380a60a0181371a0"
os = "freebsd"

    [[proxTV.download]]
    sha256 = "ff3a5ae319d085829b2406b9a5e6d275eeb922e859e845288c6307c8006fcb62"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.x86_64-unknown-freebsd.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "dfa88affbe7ebf8d383157f9360169dbcc06031a"
os = "windows"

    [[proxTV.download]]
    sha256 = "e73cdb9d2ca27da32dafb17c2b569e7e59cdd9c3004d68ebac6c60f13c8155de"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.3.2+0/proxTV.v3.3.2.x86_64-w64-mingw32.tar.gz"
