[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "c27bf6bd6cf3516f0c7da7a51aeb72ac84fc2f77"
os = "macos"

    [[proxTV.download]]
    sha256 = "81a2fd163d71ea8c0bbc62cac9423883cb4c8b184be0f3628575ab281eda05c6"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.aarch64-apple-darwin.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "bfe42bd7da563575dd46596c50043b24a17907ff"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "4718ebe9bb8417d9e6981998c00ce1df9268350069a435ca1ddff4a817a2ddee"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.aarch64-linux-gnu.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "8070de561a0bebd82b729e0e25adccab13b31c9c"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "1445da6cb7e4c155eff0cc115154c88b4e1b596f9b78ab9a8f6d51127960fe87"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.aarch64-linux-musl.tar.gz"
[[proxTV]]
arch = "aarch64"
git-tree-sha1 = "906f0c74f046ea04860fbae82c83e0d78a71057d"
os = "freebsd"

    [[proxTV.download]]
    sha256 = "639e8498e0e239217bcc1aecddde0ad5c98f40cd4b52acf01f5a1c240d3ac0be"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.aarch64-unknown-freebsd.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d1242df8d2c0b99d817ab633028507dc1910626"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "cc664bb12f7926f04f4ef3a45ecd1fe34b295c4f6878cf6585eb5c741c788a4a"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.armv6l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7d5acbeac77dfce366aac4ace5f5a0e8c34ecb5b"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "7aa1a15f2218a6d56b4e990d00fe0f56ff1966cb0dc328a7780533cb359d5750"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.armv6l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7f0f23f1e533aa0fe16f7c8b9016c5e80fabfe4"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "2ed1599b0cc99921b46a942ef16467569d29aa66f86089f014029843ce01f875"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.armv7l-linux-gnueabihf.tar.gz"
[[proxTV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "064d026ac798f20c8d86f7283f0f499b690f81a0"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "8bd697e6c69cb3c41890e1eb9cac1376c39ebaeca781a6b55764bf1e45efb00d"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.armv7l-linux-musleabihf.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "774e30bf90490cbf2f75c3c08ba285394be615b7"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "3a427a8e60097ddcfcf4557dc812caabd221bf07bd861c4b5ed22b621ee592b9"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.i686-linux-gnu.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "ffd5a0a43bc38ebd408e05405a8003238d02f44e"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "f1a27d80b1af46f85e286bb873227cd62dce9e6d1698490799ba7e63a6e4d916"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.i686-linux-musl.tar.gz"
[[proxTV]]
arch = "i686"
git-tree-sha1 = "c9e8aaee23218ef126ebf5d7d509d181440f391e"
os = "windows"

    [[proxTV.download]]
    sha256 = "48a2a5aa11aa55261a77bf14fcdb451361475733e1b7e2303ac6a82691f2fcea"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.i686-w64-mingw32.tar.gz"
[[proxTV]]
arch = "powerpc64le"
git-tree-sha1 = "10f3a3070561f76a210434bf02cad9a70f058169"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "b9ca96776e25a97e80b4a01629c6ae987d1bd56dfe2808cd3828d7083509b83c"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.powerpc64le-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "c04c516861216c1bcc81fdfd38b02d162873a86e"
os = "macos"

    [[proxTV.download]]
    sha256 = "78ce36211aecf14c560093c5d62d98a47869dace2b312cd951abd2410305a33c"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.x86_64-apple-darwin.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "d7c6132b40ffed96229dc3023fc2b51e87197bff"
libc = "glibc"
os = "linux"

    [[proxTV.download]]
    sha256 = "4be9bf7f1a9e32cdbf709f1b4614208febf46f4b44ceccb82cff6f40e7b1efb8"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.x86_64-linux-gnu.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "f4283eb2d2f7727a23cf7743f43d95f5ce148b45"
libc = "musl"
os = "linux"

    [[proxTV.download]]
    sha256 = "b5a5a3ce54ddf6756766092d3a6b173786b6f22018472147835181f4bc06824b"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.x86_64-linux-musl.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "feefef5866d06ce4efa9f2b87ffbabe906b194bd"
os = "freebsd"

    [[proxTV.download]]
    sha256 = "a5750e23eed444f8c513624485f109bcbe16179b2b155dc180d7f64f071b3882"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.x86_64-unknown-freebsd.tar.gz"
[[proxTV]]
arch = "x86_64"
git-tree-sha1 = "56bac2ec7245a6b2b89091f28ffadaf86dbcbd49"
os = "windows"

    [[proxTV.download]]
    sha256 = "384bb8663f7913c395998d6fe842469c5b0f20937f7d1310eecd65ca8e228e3d"
    url = "https://github.com/JuliaBinaryWrappers/proxTV_jll.jl/releases/download/proxTV-v3.4.0+0/proxTV.v3.4.0.x86_64-w64-mingw32.tar.gz"
