# Autogenerated wrapper script for proxTV_jll for i686-w64-mingw32
export libproxtv

using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("proxTV")
JLLWrappers.@declare_library_product(libproxtv, "libproxtv.dll")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libproxtv,
        "bin\\libproxtv.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
